FROM quay.io/opendatahub/odh-midstream-python-base-3-12:latest

ENV UV_INDEX_STRATEGY=unsafe-best-match

COPY distribution/constraints.txt ${APP_ROOT}/constraints.txt
COPY distribution/requirements.txt ${APP_ROOT}/requirements.txt
RUN uv pip install --constraint ${APP_ROOT}/constraints.txt -r ${APP_ROOT}/requirements.txt

COPY distribution/fetch_artifacts.py ${APP_ROOT}/fetch_artifacts.py
COPY --chmod=755 distribution/copy-artifacts.sh ${APP_ROOT}/copy-artifacts.sh
COPY distribution/artifacts.lock.yaml ${APP_ROOT}/artifacts.lock.yaml
RUN uv run ${APP_ROOT}/fetch_artifacts.py ${APP_ROOT}/artifacts.lock.yaml /tmp/artifacts \
    && ${APP_ROOT}/copy-artifacts.sh /tmp/artifacts \
    && rm -rf /tmp/artifacts
ENV DOCLING_ARTIFACTS_PATH="${APP_ROOT}/.cache/docling/models"
ENV TIKTOKEN_CACHE_DIR="${APP_ROOT}/.cache/tiktoken"

{config_labels}

COPY distribution/config.yaml ${APP_ROOT}/config.yaml
COPY --chmod=755 distribution/entrypoint.sh ${APP_ROOT}/entrypoint.sh

ENTRYPOINT [ "/opt/app-root/entrypoint.sh" ]
