FROM registry.access.redhat.com/ubi9/python-312@sha256:21739f35258f21e23a7e02e79c763f2a69e605416fedd54b6ec9c5ef68fd1f43
WORKDIR /opt/app-root

RUN pip install sqlalchemy # somehow sqlalchemy[asyncio] is not sufficient
{dependencies}
{llama_stack_install_source}

RUN mkdir -p ${{HOME}}/.llama ${{HOME}}/.cache
COPY distribution/run.yaml ${{APP_ROOT}}/run.yaml
COPY --chmod=755 distribution/entrypoint.sh ${{APP_ROOT}}/entrypoint.sh

#TODO: remove this once we have a stable version of llama-stack
# LLS server version is not aligned with the client version, so we disable the version check
# Currently, LLS client version is 0.3.0, while the server version is 0.3.0rc3+rhai0
ENV LLAMA_STACK_DISABLE_VERSION_CHECK=true

ENTRYPOINT [ "/opt/app-root/entrypoint.sh" ]
